# syntax=docker/dockerfile:1.4
ARG TARGETPLATFORM
FROM --platform=$TARGETPLATFORM nginxinc/nginx-unprivileged:stable-alpine

LABEL author="Hasanudin H Syafaat <banghasan@gmail.com>"

ADD default-rootless.conf /etc/nginx/conf.d/default.conf
ADD css/ /opt/www/file-browser/css/
ADD image/ /opt/www/file-browser/image/
ADD js/ /opt/www/file-browser/js/
ADD index.html /opt/www/file-browser/

VOLUME /opt/www/files/
EXPOSE 8080
